<?php
/**
 * EmailSchedulingApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AppConnect V3
 *
 * The Constant Contact, Inc. V3 public API, for building integrations with Constant Contact, the leading small-business email marketing platform.
 *
 * The version of the OpenAPI document: 3.0.2400
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ConstantContact\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EmailSchedulingApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmailSchedulingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for retrieveEmailCampaignActivityPreviewUsingGET
     *
     * GET the HTML Preview of an Email Campaign Activity.
     *
     */
    public function testRetrieveEmailCampaignActivityPreviewUsingGET()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retrieveEmailSchedulesUsingGET
     *
     * GET an Email Campaign Activity Schedule.
     *
     */
    public function testRetrieveEmailSchedulesUsingGET()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retrieveEmailSendHistoryUsingGET
     *
     * GET the Send History of an Email Campaign Activity.
     *
     */
    public function testRetrieveEmailSendHistoryUsingGET()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for scheduleEmailCampaignActivityUsingPOST
     *
     * POST (Create) an Email Campaign Activity Schedule.
     *
     */
    public function testScheduleEmailCampaignActivityUsingPOST()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for testSendCampaignActivityUsingPOST
     *
     * POST Test Send an Email Campaign Activity.
     *
     */
    public function testTestSendCampaignActivityUsingPOST()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for unscheduleEmailCampaignActivityUsingDELETE
     *
     * DELETE an Email Campaign Activity Schedule.
     *
     */
    public function testUnscheduleEmailCampaignActivityUsingDELETE()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
