<?php
/**
 * LandingPagesReportingApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ConstantContact\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AppConnect V3
 *
 * The Constant Contact, Inc. V3 public API, for building integrations with Constant Contact, the leading small-business email marketing platform.
 *
 * The version of the OpenAPI document: 3.0.2400
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ConstantContact\Client\Test\Api;

use 'ConstantContact\Client\Configuration;
use 'ConstantContact\Client\ApiException;
use 'ConstantContact\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LandingPagesReportingApiTest Class Doc Comment
 *
 * @category Class
 * @package  ConstantContact\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LandingPagesReportingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getContactAdds
     *
     * GET a Unique Contacts Adds Landing Page Report.
     *
     */
    public function testGetContactAdds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getContactOpens
     *
     * GET a Contacts Opens Landing Page Report.
     *
     */
    public function testGetContactOpens()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUniqueContactClicks
     *
     * GET a Unique Contacts Clicks Landing Page Report.
     *
     */
    public function testGetUniqueContactClicks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUniqueContactOpens
     *
     * GET a Unique Contacts Opens Landing Page Report.
     *
     */
    public function testGetUniqueContactOpens()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUniqueContactSMSOptIns
     *
     * GET a Unique Contacts SMS Opt-In Landing Page Report.
     *
     */
    public function testGetUniqueContactSMSOptIns()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUniqueContactUpdates
     *
     * GET a Unique Contacts Updates Landing Page Report.
     *
     */
    public function testGetUniqueContactUpdates()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
