<?php
/**
 * SegmentsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ConstantContact\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AppConnect V3
 *
 * The Constant Contact, Inc. V3 public API, for building integrations with Constant Contact, the leading small-business email marketing platform.
 *
 * The version of the OpenAPI document: 3.0.2400
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ConstantContact\Client\Test\Api;

use 'ConstantContact\Client\Configuration;
use 'ConstantContact\Client\ApiException;
use 'ConstantContact\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SegmentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  ConstantContact\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SegmentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createSegment
     *
     * POST (create) a Segment.
     *
     */
    public function testCreateSegment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSegment
     *
     * DELETE a Segment.
     *
     */
    public function testDeleteSegment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAccountSegments
     *
     * GET all Segments.
     *
     */
    public function testGetAccountSegments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSegmentDetail
     *
     * GET a Segment's Details.
     *
     */
    public function testGetSegmentDetail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSegment
     *
     * PUT (update) a Segment.
     *
     */
    public function testUpdateSegment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSegmentName
     *
     * PATCH (rename) a Segment.
     *
     */
    public function testUpdateSegmentName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
